### ISSUE TITLE
To-Dos after first iteration

### ISSUE THREAD

**Issue by jonasW3F** [miepsik/polkadot-selection#3]
**Some things that we discussed:**

- [x] Check if email address is properly formatted (has a @)
- [x]  Check if Polkadot address starts with "1" and has 47 characters
- [x] Don't allow to skip steps
- [x] Make it incompatible with mobile
- [x] Make the "next" button on step 4 inactive as long as the user did not complete all pairwise comparisons.
- [x] Properly format the checkbox on "Step 2" that it says "I have read and agree with the Data Collection and Privacy Agreement above"

**Tables:**
- [x]  First row should be sticky when scrolling down
- [x]  Column names should be proper names (self_stake -> Self-Stake). 
- [x]  Add info to column names (Self Stake (in DOT), Total Stake (in DOT), Commission (in %))
- [x]  Voters and Cluster Size need to be switched
- [x] Round values in table 
- [x] Have a "?" on each column name which shows the explanation of the variable again by hovering over.
- [x] Style table with columns descriptions (step3)
- [x] Make it possible to order by column
- [x] In algorithm selection: Show some info text after 5/5 (i.e., "You are done with your selection") text is returned but not displayed
- [x]  Final selection having a single table (question is to add a new column which indicates from where the selection comes from)
- [x] Show the algorithm recommendation as last part of the pairwise comparisons.

**Info-Texts**
- [x]  Footers: Add more meaningful info instead of explaining the UI.
- [x] Info text of Selection A: You cannot add more than 7 validators
- [x] Change "submit" in stage 5 to "next" to be more in line with the flow.
- [x] Style box with validation messages on step1 and step2
- [x] Style box with cookies info (step1)
- [x] Add info about funding by Treasury to the study somewhere (preferably front page)
- [x] Adjust Selection C info text.
- [x] Properly format criteria explanations in step 3

**Questionnaire**
- [x] Include the following questions: https://hackmd.io/@8F4MrJhQT32fynUEzuSsHA/H1wZgeWe9
   - [x] Make "IF"-questions only show if the condition is met
   - [x] Have the"percent"-answers only allow between 0 and 100
   - [x] Make questions required
   - [x] Style table with recommendations

**Backend**
- [x] Have the login page check the code with a database in the backend.
- [x] Record time on each page
- [x] Populate data set with user's data

**Comment by jonasW3F** [comment]
A draft for the variable explanations:
- **Total-Stake:** The total amount of DOT that the validator is staking. All other criteria being equal, a lower total stake means that your stake has a larger share and increases your payoff.
- **Self-Stake:** The amount of DOT that the validator is using to nominate themselves. Since this amount is slashable, a higher amount generally means that the validator has more skin-in-the-game.
- **Voters**: The number of nominators that are voting for a validator. Could be regarded as a sign of popularity.
- **Cluster-Size**: The number of (known) validators that are operated by the same entity. A higher number might indicate higher proficiency but could also indicate more centralization and a higher risk of getting slashed.
- **Commission**: How much the validator is charging for their services. A lower commission, all other criteria being equal, means more reward for the nominator. A higher commission of an active validator indicates more skin-in-the-game of that validator because they would miss more future rewards for getting slashed.
- **Era-Points**: The total rewards to all validators is distributed based on the relative share of the era-points of one validator compared to other validators. Should be similar over time but can fluctuate based on the infrastructure and location of a validator.

**Comment by rmnprkrl** [comment]
url: http://research-vs.w3f.tech/step1.php

> * [x]  Check if email address is properly formatted (has a @)
> * [x]   Check if Polkadot address starts with "1" and has 47 characters
> * [x]  Don't allow to skip steps
> * [x]  Make it incompatible with mobile
> * [x]  Make the "next" button on step 4 inactive as long as the user did not complete all pairwise comparisons.
> * [x]  Properly format the checkbox on "Step 2" that it says "I have read and agree with the Data Collection and Privacy Agreement above"
> 
> **Tables:**
> 
> * [x]   First row should be sticky when scrolling down
> * [x]   Column names should be proper names (self_stake -> Self-Stake).
> * [x]   Add info to column names (Self Stake (in DOT), Total Stake (in DOT), Commission (in %))
> * [x]   Voters and Cluster Size need to be switched
> * [x]  Round values in table
> * [x]  Have a "?" on each column name which shows the explanation of the variable again by hovering over.
> * [x]  Style table with columns descriptions (step3)
> * [x]  Make it possible to order by column
> * [x]  In algorithm selection: Show some info text after 5/5 (i.e., "You are done with your selection") text is returned but not displayed
> * [x]   Final selection having a single table (question is to add a new column which indicates from where the selection comes from)
> * [x]  Show the algorithm recommendation as last part of the pairwise comparisons.
> 
> **Info-Texts**
> 
> * [x]   Footers: Add more meaningful info instead of explaining the UI.
> * [x]  Info text of Selection A: You cannot add more than 7 validators
> * [x]  Change "submit" in stage 5 to "next" to be more in line with the flow.
> * [x]  Style box with validation messages on step1 and step2
> * [x]  Style box with cookies info (step1)
> * [x]  Add info about funding by Treasury to the study somewhere (preferably front page)
> * [x]  Adjust Selection C info text.
> * [x]  Properly format criteria explanations in step 3
> 
> **Questionnaire**
> 
> * [x]  Include the following questions: https://hackmd.io/@8F4MrJhQT32fynUEzuSsHA/H1wZgeWe9
>   
>   * [x]  Make "IF"-questions only show if the condition is met
>   * [x]  Have the"percent"-answers only allow between 0 and 100
>   * [x]  Make questions required
>   * [x]  Style table with recommendations
> 
> **Backend**
> 
> * [x]  Have the login page check the code with a database in the backend.
> * [x]  Record time on each page
> * [x]  Populate data set with user's data

**Comment by jonasW3F** [comment]
Seems all fixed, great.
